version: "3.7"

services:
    vote:
        build: ./PoC-vote
        volumes:
            - type: bind
              source: ./PoC-vote/vote_app
              target: /app
        networks:
            - front-tier
            - back-tier
        ports:
            - "8000:8000"
        depends_on:
            - "super-redis"

    worker:
        build: ./PoC-worker
        volumes:
            - type: bind
              source: ./PoC-worker/worker_app
              target: /app
        networks:
            - back-tier
        depends_on:
            - "super-redis"
            - "super-db"

    result:
        build: ./PoC-result
        networks:
            - front-tier
            - back-tier
        ports:
            - "8080:8080"
        depends_on:
            - "super-db"

    super-redis:
        image: redis:6.0.10-alpine
        container_name: super-redis
        ports: ["6379"]
        networks:
            - back-tier

    super-db:
        image: postgres:13.1-alpine
        container_name: super-db
        environment:
            PGHOST: "super-db"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
        ports:
            - "5432:5432"
        volumes:
            - "db-data:/var/lib/postgresql/data"
        networks:
            - back-tier

volumes:
    db-data:

networks:
    front-tier:
    back-tier:
